service:
  name: flight-service
  port: ${GRPC_PORT:50051}

spring:
  datasource:
    url: jdbc:postgresql://${FLIGHT_DB_HOST:localhost}:${FLIGHT_DB_PORT:5433}/${FLIGHT_DB_NAME:flight}?ssl=false
    username: ${FLIGHT_DB_USER:postgres}
    password: ${FLIGHT_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
